#!/usr/bin/python

# gHost - Devin Shoemaker 2019-02-28
# retrieves vhost for a specific site on cPanel servers 
# https://github.com/tailwag/ghost
# usage:
#       $ ghost example.com
#       $ ghost /home/user/public_html

import os 
import re
import sys 
import subprocess

search = sys.argv[1]

# retrieve whole httpd.conf
conf = subprocess.Popen(["sudo", "cat", "/etc/apache2/conf/httpd.conf"], stdout=subprocess.PIPE).communicate()[0]

# convert httpd.conf into list by line
vhost = conf.split('\n')

# define regex for searching by domanin name 
if os.path.isdir(search):
    serverna = re.compile(r'\s{2}DocumentRoot\s'+search)
else:
    serverna = re.compile(r'\s{2}Server(Name|Alias).*?\s'+search+'.*?')

# return line searched for 
found = list(filter(serverna.match, vhost))[-1]

# get line number of returned line
check = [i for i, x in enumerate(vhost) if x == found][-1]

vbegin=check
vend=check

# matched opening and closing vhost tag 
vline = re.compile(r'</?VirtualHost.*?>')

while vbegin <= check:
    grep = vline.search(vhost[vbegin])
    if grep != None:
        break
    vbegin -= 1

while vend >= check:
    grep = vline.search(vhost[vend])
    if grep != None:
        break
    vend += 1

prog=vbegin

while prog <= vend:
    print(vhost[prog])
    prog += 1

